services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=buy01-db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    command: [--auth]
    ports:
      - '27017:27017'
    restart: always

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/buy01-db?authSource=admin
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - zookeeper
      - kafka

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/buy01-db?authSource=admin
    ports:
      - '8081:8080'
    depends_on:
      - mongodb
      - zookeeper
      - kafka

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/buy01-db?authSource=admin
    ports:
      - '8082:8080'
    depends_on:
      - mongodb
      - zookeeper
      - kafka

  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./angular/cert:/etc/nginx/ssl:ro

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    expose:
      - '9093'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs-1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "token-validation-request:1:1,token-validation-response:1:1"
    depends_on:
      - zookeeper
